---

# Variables
- name: Install phase
  ansible.builtin.include_tasks:
    file: vars.yml

# Install phase
- name: Install phase
  ansible.builtin.include_tasks:
    file: install.yml

# Config phase
- name: Configursation phase
  ansible.builtin.include_tasks:
    file: config-{{ ansible_os_family }}.yml

