---

- name: Load variables based on OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "vars"

# Install phase
- name: Install phase
  ansible.builtin.include_tasks:
    file: install.yml

# Config phase
- name: Configursation phase
  ansible.builtin.include_tasks:
    file: config-{{ ansible_os_family }}.yml

