---

- name: Restart apache
  ansible.builtin.service:
    name: "{{ php_apache_service }}"
    state: restarted

- name: Restart fpm
  ansible.builtin.service:
    name: "{{ php_fpm_service }}"
    state: restarted
